import type { ArenaRun } from '../domain.js';

export interface ImageGenConfig {
  apiKey: string | undefined;
  baseUrl: string;
  model: string;
  requestFormat: 'openai' | 'legacy';
  timeoutMs: number;
}

function parsePositiveNumber(input: string | undefined, fallback: number): number {
  const parsed = Number(input);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

export function getImageGenConfig(): ImageGenConfig {
  return {
    apiKey: process.env.IMAGE_API_KEY ?? process.env.XAI_API_KEY,
    baseUrl: (process.env.IMAGE_BASE_URL || 'https://xais.dchai.cn/xais').replace(/\/+$/, ''),
    model: process.env.IMAGE_MODEL || 'Nano_Banana_Pro_4K_0',
    requestFormat: process.env.IMAGE_API_FORMAT === 'legacy' ? 'legacy' : 'openai',
    timeoutMs: parsePositiveNumber(process.env.IMAGE_REQUEST_TIMEOUT_MS, 45_000),
  };
}

export function getImageEnvStatus(): {
  hasApiKey: boolean;
  apiKeyPreview: string | null;
  baseUrl: string;
  model: string;
} {
  const config = getImageGenConfig();
  const apiKey = config.apiKey;
  return {
    hasApiKey: !!apiKey,
    apiKeyPreview: apiKey ? `${apiKey.slice(0, 8)}...${apiKey.slice(-4)}` : null,
    baseUrl: config.baseUrl,
    model: config.model,
  };
}

export interface GeneratePosterRequest {
  topic: string;
  mode: string;
  participants: Array<{
    displayName: string;
    stageLabel: string;
  }>;
  summary?: {
    title?: string;
    consensus?: string;
    narrativeHook?: string;
    disagreements?: string[];
    actionableAdvice?: string[];
  };
  stylePrompt?: string;
  imageSize?: string;
}

export interface GeneratePosterResponse {
  ok: boolean;
  imageUrl?: string;
  imageBase64?: string;
  model: string;
  error?: string;
  prompt: string;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function truncateForPoster(value: string, maxChars: number): string {
  const normalized = value.replace(/\s+/g, ' ').trim();
  if (normalized.length <= maxChars) {
    return normalized;
  }
  return `${normalized.slice(0, Math.max(0, maxChars - 1)).trim()}…`;
}

function buildFallbackPosterDataUrl(request: GeneratePosterRequest): string {
  const width = 768;
  const height = 1024;
  const participants = request.participants.slice(0, 4);
  const title = escapeXml(truncateForPoster(request.topic, 34));
  const consensus = escapeXml(truncateForPoster(request.summary?.consensus || '这场跨阶段对话已生成结构化洞察。', 86));
  const advice = (request.summary?.actionableAdvice || []).slice(0, 3);
  const roleRows = participants.map((participant, index) => {
    const y = 360 + index * 92;
    return `
      <rect x="72" y="${y}" width="624" height="68" rx="18" fill="${index % 2 === 0 ? '#F4FBF8' : '#F8F5FF'}" stroke="#D9E7E2"/>
      <text x="104" y="${y + 29}" font-size="25" font-weight="700" fill="#1F2A2E">${escapeXml(participant.displayName)}</text>
      <text x="104" y="${y + 54}" font-size="20" fill="#65736F">${escapeXml(participant.stageLabel)}</text>`;
  }).join('');
  const adviceRows = advice.map((item, index) => {
    const y = 760 + index * 54;
    return `
      <circle cx="92" cy="${y - 7}" r="15" fill="#29685A"/>
      <text x="87" y="${y}" font-size="18" font-weight="700" fill="#FFFFFF">${index + 1}</text>
      <text x="124" y="${y}" font-size="22" fill="#26332F">${escapeXml(truncateForPoster(item, 28))}</text>`;
  }).join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#F6F1E8"/>
        <stop offset="0.55" stop-color="#EAF7F1"/>
        <stop offset="1" stop-color="#EEF0FF"/>
      </linearGradient>
    </defs>
    <rect width="768" height="1024" fill="url(#bg)"/>
    <rect x="48" y="48" width="672" height="928" rx="34" fill="rgba(255,255,255,0.82)" stroke="#D8DED9"/>
    <text x="72" y="120" font-size="26" font-weight="700" fill="#29685A">时序人格会议海报</text>
    <text x="72" y="190" font-size="45" font-weight="800" fill="#182421">${title}</text>
    <rect x="72" y="232" width="624" height="86" rx="22" fill="#172A26"/>
    <text x="104" y="267" font-size="23" font-weight="700" fill="#FFFFFF">核心共识</text>
    <text x="104" y="298" font-size="20" fill="#DBECE6">${consensus}</text>
    <text x="72" y="340" font-size="27" font-weight="800" fill="#182421">参会人格</text>
    ${roleRows}
    <text x="72" y="716" font-size="27" font-weight="800" fill="#182421">行动建议</text>
    ${adviceRows || '<text x="72" y="780" font-size="22" fill="#26332F">保留分歧，先做低成本验证。</text>'}
    <text x="72" y="930" font-size="20" fill="#65736F">Generated by Time Persona Backend</text>
  </svg>`;

  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

function buildPosterPrompt(request: GeneratePosterRequest): string {
  const participants = request.participants.map(p => p.displayName).join('、');
  const topic = request.topic;
  const isDebate = request.mode === 'debate';
  const mode = isDebate ? '辩论' : '圆桌讨论';
  const consensus = request.summary?.consensus || '';
  const disagreements = request.summary?.disagreements?.join('；') || '';
  const advice = request.summary?.actionableAdvice?.slice(0, 3).map((a, i) => `${i + 1}. ${a}`).join('  ') || '';
  const customStyle = request.stylePrompt || '';

  const prompt = `信息图风格知识科普海报，中文排版，竖版布局，从上到下分为清晰的模块区域。

【顶部区域】
- 大号加粗主标题："${topic}"
- 副标题/引言：${consensus || mode + '精华总结'}

${isDebate ? `【中间上部：双栏对比区】
- 左右对称两栏布局，用对比色区分两个阵营
- 左栏标题标注第一个阵营的核心判断，右栏标注第二个阵营的核心判断
- 每栏包含3个带扁平化矢量图标的要点
- 每栏底部有对话气泡，引用${participants}的关键发言` : `【中间上部：角色观点区】
- ${participants}每人一个卡片模块
- 每个卡片包含角色名、核心观点、带图标的要点
- 卡片之间用连接线或箭头表示对话关系`}

${disagreements ? `【中间：核心分歧区】
- 居中标题"核心分歧"
- 双向箭头连接对立观点：${disagreements}
- 用醒目的对比色（如红vs蓝）区分不同立场` : ''}

${advice ? `【中下部：行动建议区】
- 三栏卡片式布局，带数字序号和对勾图标
- 内容：${advice}` : ''}

【底部区域】
- 深色高亮背景的最终结论区
- 简洁有力的总结语

整体风格要求：
- 扁平化矢量图标，简约无衬线中文字体
- 模块化卡片设计，圆角矩形，信息层级清晰
- 配色根据主题灵活变化：可使用渐变色、对比色、互补色等，每次生成尝试不同的配色方案，如深蓝配金色、紫红配青绿、暖橙配深灰、翡翠绿配珊瑚粉等
- 背景干净专业，可以是浅色、深色或渐变背景
- 易读性强，类似微信公众号知识科普长图的排版风格
- 不需要人物照片，用图标和文字传达信息
${customStyle}`;

  return prompt;
}

export async function generatePoster(request: GeneratePosterRequest): Promise<GeneratePosterResponse> {
  const config = getImageGenConfig();

  if (!config.apiKey) {
    const prompt = buildPosterPrompt(request);
    const fallbackPoster = buildFallbackPosterDataUrl(request);
    return { ok: true, imageUrl: fallbackPoster, imageBase64: fallbackPoster, model: config.model, prompt };
  }

  const prompt = buildPosterPrompt(request);
  const imageSize = request.imageSize || '1024x1024';
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), config.timeoutMs);
  const body = config.requestFormat === 'legacy'
    ? {
        model: config.model,
        prompt,
        image_size: imageSize,
        batch_size: 1,
        num_inference_steps: 20,
        guidance_scale: 7.5,
      }
    : {
        model: config.model,
        prompt,
        size: imageSize,
        n: 1,
        response_format: 'url',
      };

  try {
    const response = await fetch(`${config.baseUrl}/v1/images/generations`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`,
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    if (!response.ok) {
      const errorText = await response.text();
      const fallbackPoster = buildFallbackPosterDataUrl(request);
      return { ok: true, imageUrl: fallbackPoster, imageBase64: fallbackPoster, model: config.model, prompt, error: `图片生成请求失败: ${response.status} - ${errorText}` };
    }

    const data = await response.json() as {
      images?: Array<{ url?: string }>;
      data?: Array<{ url?: string; b64_json?: string }>;
      timings?: Record<string, unknown>;
      seed?: number;
    };

    const imageUrl = data.data?.[0]?.url ?? data.images?.[0]?.url;
    const imageBase64FromApi = data.data?.[0]?.b64_json ? `data:image/png;base64,${data.data[0].b64_json}` : undefined;

    if (!imageUrl && !imageBase64FromApi) {
      const fallbackPoster = buildFallbackPosterDataUrl(request);
      return { ok: true, imageUrl: fallbackPoster, imageBase64: fallbackPoster, model: config.model, prompt, error: '图片生成成功但未返回URL或base64' };
    }

    let imageBase64: string | undefined = imageBase64FromApi;
    if (imageUrl) {
      try {
        const imgResponse = await fetch(imageUrl);
        if (imgResponse.ok) {
          const buffer = await imgResponse.arrayBuffer();
          const base64 = Buffer.from(buffer).toString('base64');
          imageBase64 = `data:image/png;base64,${base64}`;
        }
      } catch {
        // 图片 URL 下载失败时仍返回原始 URL。
      }
    }

    return {
      ok: true,
      imageUrl: imageUrl ?? imageBase64,
      imageBase64,
      model: config.model,
      prompt,
    };
  } catch (error) {
    const fallbackPoster = buildFallbackPosterDataUrl(request);
    return { ok: true, imageUrl: fallbackPoster, imageBase64: fallbackPoster, model: config.model, prompt, error: error instanceof Error ? error.message : '图片生成失败' };
  } finally {
    clearTimeout(timeout);
  }
}

export async function generatePosterFromRun(run: ArenaRun, stylePrompt?: string): Promise<GeneratePosterResponse> {
  return generatePoster({
    topic: run.topic,
    mode: run.mode,
    participants: run.participants.map(p => ({
      displayName: p.displayName,
      stageLabel: p.stageLabel,
    })),
    summary: run.summary,
    stylePrompt,
  });
}
